import { IoLocationSharp } from "react-icons/io5";
import { PiAirplaneTakeoffFill } from "react-icons/pi";
import { MdSchool } from "react-icons/md";
import { FaChalkboardTeacher } from "react-icons/fa";

export const NavRoutes = [
  { label: "ლოკალური", icon: IoLocationSharp, route: "Local" },
  { label: "გაცვლითი", icon: PiAirplaneTakeoffFill, route: "Exchanges" },
  { label: "უნივერსიტეტები", icon: MdSchool, route: "Universities" },
  { label: "მენტორი", icon: FaChalkboardTeacher, route: "Mentors" },
];

export const filterElementsLocal = [
  {
    name: "ქვეყანა",
    answers: [
      "საქართველო",
      "ესპანეთი",
      "ინგლისი",
      "ამერიკა",
      "იტალია",
      "საფრანგეთი",
    ],
  },
  {
    name: "ასაკი",
    answers: ["0-12", "12-18", "18 - 35"],
  },
  {
    name: "ორგანიზაცია",
    answers: ["AISEC", "YCG", "ERASMUS"],
  },
  {
    name: "თარიღი",
    answers: ["მიმდინარე", "მომავალი", "მოკლე პერიოდი"],
  },
  {
    name: "ბიუჯეტი",
    answers: ["დაუფინანსებელი", "ნაწილობრივ", "დაფინანსებული"],
  },
];

export const exchangePrograms = [
  {
    id: "1",
    name: "Global Learning in Tbilisi",
    age: "18-30",
    financeType: "Scholarship",
    moneyAmount: "5000 USD",
    period: "6 months",
    sendingOrganisation: "Global Scholars",
    hostingOrganisation: "Tbilisi University",
    formDedline: "2025-06-30",
    sendDate: "2025-09-01",
    backDate: "2026-03-01",
    registrationForm: "http://example.com/form1",
    description: "A global learning program in Tbilisi, Georgia.",
    images: ["http://example.com/img1.jpg"],
    country: "Georgia",
    criteriums: "Must be a student",
    ScolarshipDescription: "Full scholarship covering all expenses",
    isNotSponsored: "No",
    additionalInfo: "Exciting program for university students",
    location: { lat: 41.6938, lng: 44.8015 }, // Tbilisi, Georgia
  },
  {
    id: "2",
    name: "Cultural Exchange in Dublin",
    age: "20-35",
    financeType: "Self-Funded",
    moneyAmount: "3000 USD",
    period: "4 months",
    sendingOrganisation: "International Exchange Org",
    hostingOrganisation: "Dublin Cultural Center",
    formDedline: "2025-07-15",
    sendDate: "2025-10-01",
    backDate: "2026-02-01",
    registrationForm: "http://example.com/form2",
    description: "Cultural exchange program in Dublin, Ireland.",
    images: ["http://example.com/img2.jpg"],
    country: "Ireland",
    criteriums: "Must have a valid passport",
    ScolarshipDescription: "None",
    isNotSponsored: "Yes",
    additionalInfo: "Great opportunity to learn about Irish culture",
    location: { lat: 53.3498, lng: -6.2603 }, // Dublin, Ireland
  },
  {
    id: "3",
    name: "STEM Exchange in Odenton",
    age: "18-25",
    financeType: "Partial Scholarship",
    moneyAmount: "2000 USD",
    period: "5 months",
    sendingOrganisation: "STEM Education Network",
    hostingOrganisation: "Odenton Institute of Tech",
    formDedline: "2025-05-30",
    sendDate: "2025-08-15",
    backDate: "2026-01-15",
    registrationForm: "http://example.com/form3",
    description: "STEM exchange program in Odenton, USA.",
    images: ["http://example.com/img3.jpg"],
    country: "USA",
    criteriums: "Passion for STEM subjects",
    ScolarshipDescription: "Partial scholarship for tuition",
    isNotSponsored: "No",
    additionalInfo: "Ideal for students pursuing a career in STEM",
    location: { lat: 39.0458, lng: -76.6413 }, // Odenton, USA
  },
  {
    id: "4",
    name: "Artistic Residency in Nantes",
    age: "21-40",
    financeType: "Self-Funded",
    moneyAmount: "4000 EUR",
    period: "3 months",
    sendingOrganisation: "Artists Abroad",
    hostingOrganisation: "Nantes Art Residency",
    formDedline: "2025-08-10",
    sendDate: "2025-11-01",
    backDate: "2026-02-01",
    registrationForm: "http://example.com/form4",
    description: "Artistic residency program in Nantes, France.",
    images: ["http://example.com/img4.jpg"],
    country: "France",
    criteriums: "Must be an artist",
    ScolarshipDescription: "None",
    isNotSponsored: "Yes",
    additionalInfo: "Open to artists from all backgrounds",
    location: { lat: 47.21725, lng: -1.55336 }, // Nantes, France
  },
  {
    id: "5",
    name: "Entrepreneurship in Angers",
    age: "22-35",
    financeType: "Scholarship",
    moneyAmount: "6000 EUR",
    period: "4 months",
    sendingOrganisation: "Entrepreneurship Initiative",
    hostingOrganisation: "Angers Business School",
    formDedline: "2025-09-01",
    sendDate: "2025-11-15",
    backDate: "2026-03-15",
    registrationForm: "http://example.com/form5",
    description: "Entrepreneurship program in Angers, France.",
    images: ["http://example.com/img5.jpg"],
    country: "France",
    criteriums: "Must have a business idea",
    ScolarshipDescription: "Full scholarship available",
    isNotSponsored: "No",
    additionalInfo: "Designed for aspiring entrepreneurs",
    location: { lat: 47.51725, lng: -0.55636 }, // Angers, France
  },
];
